version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=streak_tracker
      - POSTGRES_USER=streak_tracker
      - POSTGRES_PASSWORD=streak_tracker
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
