version: '3.8'
services:
  db-dev:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=streak_tracker
      - POSTGRES_USER=streak_tracker
      - POSTGRES_PASSWORD=streak_tracker
    ports:
      - '5432:5432'
    volumes: 
      - db-dev:/var/lib/postgresql/data

  db-test:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=streak_tracker
      - POSTGRES_USER=streak_tracker
      - POSTGRES_PASSWORD=streak_tracker
    ports:
      - '5433:5432'
    volumes: 
      - db-test:/var/lib/postgresql/data

volumes:
  db-dev:
  db-test:
